MinimalBlog/Controllers/DBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MinimalBlog.ViewModels;
using Services.Contracts;

namespace MinimalBlog.Controllers
{
    [Authorize]
    public class DBoardController : Controller
    {
        private readonly IUnitOfWork _service;
        private readonly UserManager<User> _userManager;

        public DBoardController(IUnitOfWork service,UserManager<User> userManager)
        {
            _service = service;
            _userManager = userManager;
        }

        public IActionResult Dashboard()
        {

            var userId = _userManager.GetUserId(HttpContext.User);

            var posts = _service.Post.GetAllPostsByAuthorId(userId);

            var fullName = _service.User.GetUserFullName(userId);
            ViewBag.FullName = fullName;
            return View(posts);
        }

        //[HttpPost]
        //public IActionResult Dashboard(string smt)
        //{
        //    return View();
        //}

        public IActionResult Createpost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Createpost(NewPostVM model)
        {

            if (ModelState.IsValid) 
            {
                var userId = _userManager.GetUserId(HttpContext.User);

                Post post = new Post
                {
                    Title = model.Title,
                    Content = model.Content,
                    Thumb = model.Thumb,
                    Category = model.Category,
                    Date = DateTime.Now,
                    AuthorId = userId
                };

                _service.Post.Create(post);
                _service.Commit();
                return RedirectToAction("Dashboard");
            }

            return View(model);
        }

    }
}

MinimalBlog/Views/DBoard/Createpost.cshtml
@model NewPostVM
@{
    ViewData["Title"] = "Createpost";
    Layout = "~/Views/Shared/Layouts/_CreatepostLayout.cshtml";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Create New Post</h1>
    </div>

    <div class="container justify-content-center">

        <!-- New Blog Post - START -->
        <div class="container">
            <div class="row" id="row_style">
                <form asp-controller="DBoard" asp-action="Createpost" method="post" class="">
                    <div class="form-group">
                        <input asp-for="Title" type="text" class="form-control" placeholder="Title">
                    </div>
                    <textarea asp-for="Content" id="editor" cols="30" rows="10">Submit your text post here...</textarea>
                    <br>
                    <div class="form-group">
                        <input asp-for="Thumb" type="text" class="form-control" placeholder="Thumb">
                    </div>
                    <div class="form-group">
                        <input asp-for="Category" type="text" class="form-control" placeholder="Tags">
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" id="submit">Submit new post</button>
                    </div>
                </form>
            </div>
        </div>

        <!-- you need to include the shieldui css and js assets in order for the charts to work -->
        <link rel="stylesheet" type="text/css" href="https://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
        <script type="text/javascript" src="https://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>

        <script>
            $(function () {
                $("#editor").shieldEditor({
                    height: 260
                });
            })
        </script>
        <!-- New Blog Post - END -->
    </div>
</main>

MinimalBlog/Views/DBoard/Dashboard.cshtml
@model IEnumerable<Post>
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/Layouts/_DashboardLayout.cshtml";
}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">My Posts</h1>
    </div>
    <div class="row mb-2">
        @foreach (var post in Model)
        {
            <div class="col-md-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-success">@post.Category</strong>
                        <h3 class="mb-0">@post.Title</h3>
                        <div class="mb-1 text-muted">@post.Date | @post.Author.FirstName @post.Author.LastName </div>
                        <p class="mb-auto">@post.Content </p>
                        <a href="singlepost.html" class="stretched-link">Continue reading</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="@post.Thumb" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                    </div>
                </div>
            </div>
        }


        @*<div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">#Design</strong>
                    <h3 class="mb-0">Post title</h3>
                    <div class="mb-1 text-muted">Nov 12 | Author</div>
                    <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">#Design</strong>
                    <h3 class="mb-0">Post title</h3>
                    <div class="mb-1 text-muted">Nov 12 | Author</div>
                    <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">#Design</strong>
                    <h3 class="mb-0">Post title</h3>
                    <div class="mb-1 text-muted">Nov 12 | Author</div>
                    <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-success">#Design</strong>
                    <h3 class="mb-0">Post title</h3>
                    <div class="mb-1 text-muted">Nov 12 | Author</div>
                    <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
                    <a href="#" class="stretched-link">Continue reading</a>
                </div>
                <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
                </div>
            </div>
        </div>*@
    </div>

</main>